C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1006,5): warning MSB8027: 이름이 context.c인 둘 이상의 파일이 같은 위치에 출력을 생성합니다. 이로 인해 잘못된 빌드 결과가 나타날 수 있습니다.  관련된 파일은 Modules\_decimal\libmpdec\context.c, Python\context.c입니다.
  arraymodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\arraymodule.c(7,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  atexitmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\atexitmodule.c(9,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  audioop.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\audioop.c(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  binascii.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\binascii.c(58,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  multibytecodec.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\multibytecodec.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_cn.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_hk.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_iso2022.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_jp.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_kr.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecs_tw.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cjkcodecs\cjkcodecs.h(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  cmathmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\cmathmodule.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  errnomodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\errnomodule.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  xmlparse.c
  xmlrole.c
  xmltok.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\expat\xmltok.c(1,1): warning C4819: 현재 코드 페이지(949)에서 표시할 수 없는 문자가 파일에 들어 있습니다. 데이터가 손실되지 않게 하려면 해당 파일을 유니코드 형식으로 저장하십시오.
  xmltok_impl.c
  xmltok_ns.c
  faulthandler.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\faulthandler.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  fcntlmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\fcntlmodule.c(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  gcmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\gcmodule.c(26,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  getaddrinfo.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(84,5): error C2061: 구문 오류: 식별자 'u_char'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(85,17): error C2061: 구문 오류: 식별자 'si_family'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(85,17): error C2059: 구문 오류: ';'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(86,17): error C2061: 구문 오류: 식별자 'si_port'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(86,17): error C2059: 구문 오류: ';'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(87,1): error C2059: 구문 오류: '}'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(107,13): error C2065: 'PF_INET': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(107,37): error C2027: 정의되지 않은 형식 'in_addr'을(를) 사용했습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(107): message : 'in_addr' 선언을 참조하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(108,32): error C2027: 정의되지 않은 형식 'sockaddr_in'을(를) 사용했습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(108): message : 'sockaddr_in' 선언을 참조하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(109,33): error C2143: 구문 오류: ')'이(가) '형식' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(109,43): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(111,29): error C2059: 구문 오류: ','
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(204,37): error C2065: 'EAI_MAX': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(205,24): error C2065: 'EAI_MAX': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(215,20): error C2037: 'ai_next'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(216,17): error C2037: 'ai_canonname'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(217,22): error C2037: 'ai_canonname'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(220,33): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(220,33): warning C4047: '!=': 'addrinfo *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(239,29): error C2079: 'sentinel'은(는) 정의되지 않은 struct 'addrinfo'을(를) 사용합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(240,32): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(244,23): error C2079: 'ai'은(는) 정의되지 않은 struct 'addrinfo'을(를) 사용합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(246,13): error C2065: 'u_short': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(246,13): error C2146: 구문 오류: ';'이(가) 'port' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(246,17): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(263,14): error C2224: '.ai_next' 왼쪽에는 구조체/공용 구조체 형식이 있어야 합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(263,28): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(264,20): warning C4133: '=': 'int *'과(와) 'addrinfo *' 사이의 형식이 호환되지 않습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(265,14): warning C4133: '=': 'int *'과(와) 'addrinfo *' 사이의 형식이 호환되지 않습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(266,10): error C2037: 'ai_flags'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(267,10): error C2037: 'ai_family'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(267,31): error C2065: 'PF_UNSPEC': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(268,10): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(269,10): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(270,10): error C2037: 'ai_addrlen'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(271,10): error C2037: 'ai_canonname'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(271,29): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(272,10): error C2037: 'ai_addr'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(272,24): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(273,10): error C2037: 'ai_next'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(273,24): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(274,10): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(276,26): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(276,26): warning C4047: '==': 'const char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(276,45): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(276,45): warning C4047: '==': 'const char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(277,26): error C2065: 'EAI_NONAME': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(280,20): error C2037: 'ai_addrlen'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(280,41): error C2037: 'ai_canonname'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(281,20): error C2037: 'ai_addr'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(281,38): error C2037: 'ai_next'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(282,13): error C2065: 'EAI_BADHINTS': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(283,20): error C2037: 'ai_flags'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(283,39): error C2065: 'AI_MASK': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(284,13): error C2065: 'EAI_BADFLAGS': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(285,24): error C2037: 'ai_family'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(286,23): error C2065: 'PF_UNSPEC': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(287,21): error C2065: 'PF_INET': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(293,13): error C2065: 'EAI_FAMILY': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(295,40): error C2027: 정의되지 않은 형식 'addrinfo'을(를) 사용했습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(133): message : 'addrinfo' 선언을 참조하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(296,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(298,26): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(301,29): error C2065: 'IPPROTO_UDP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(302,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(302,46): error C2065: 'SOCK_DGRAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(304,29): error C2065: 'IPPROTO_TCP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(305,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(305,47): error C2065: 'SOCK_STREAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(308,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(308,44): error C2065: 'SOCK_RAW': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(312,22): error C2065: 'SOCK_RAW': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(314,24): error C2065: 'SOCK_DGRAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(315,22): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(315,49): error C2065: 'IPPROTO_UDP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(316,22): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(317,17): error C2065: 'EAI_BADHINTS': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(318,18): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(318,43): error C2065: 'IPPROTO_UDP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(320,25): error C2065: 'SOCK_STREAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(321,22): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(321,49): error C2065: 'IPPROTO_TCP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(322,22): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(323,17): error C2065: 'EAI_BADHINTS': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(324,18): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(324,43): error C2065: 'IPPROTO_TCP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(327,13): error C2065: 'EAI_SOCKTYPE': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(337,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(339,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(339,46): error C2065: 'SOCK_DGRAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(340,22): error C2037: 'ai_protocol'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(340,47): error C2065: 'IPPROTO_UDP': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(342,18): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(342,34): error C2065: 'u_short': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(342,35): error C2146: 구문 오류: ')'이(가) 'atoi' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(347,25): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(347,25): warning C4047: '=': 'const char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(348,26): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(350,29): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(350,29): warning C4047: '=': 'const char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(352,28): error C2065: 'SOCK_DGRAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(355,29): error C2065: 'SOCK_STREAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(359,31): error C2065: 'stderr': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(362,53): warning C4047: '=': 'servent *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(362,62): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(362,62): warning C4047: '==': 'servent *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(363,17): error C2065: 'EAI_SERVICE': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(364,18): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(364,24): error C2037: 's_port'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'servent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(365,22): error C2037: 'ai_socktype'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'addrinfo'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(366,32): error C2037: 's_proto'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'servent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getaddrinfo.c(366,32): fatal error C1003: 오류 수가 100개를 초과했습니다. 컴파일을 중지합니다.
  getbuildinfo.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getbuildinfo.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  getnameinfo.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(65,13): error C2065: 'PF_INET': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(65,37): error C2027: 정의되지 않은 형식 'in_addr'을(를) 사용했습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(65): message : 'in_addr' 선언을 참조하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(65,65): error C2027: 정의되지 않은 형식 'sockaddr_in'을(를) 사용했습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(65): message : 'sockaddr_in' 선언을 참조하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(66,36): error C2143: 구문 오류: ')'이(가) '형식' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(66,46): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(67,14): error C2059: 구문 오류: ','
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(71,5): error C2061: 구문 오류: 식별자 'u_char'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(72,17): error C2061: 구문 오류: 식별자 'si_family'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(72,17): error C2059: 구문 오류: ';'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(73,17): error C2061: 구문 오류: 식별자 'si_port'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(73,17): error C2059: 구문 오류: ';'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(74,1): error C2059: 구문 오류: '}'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(101,13): error C2065: 'u_short': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(101,13): error C2146: 구문 오류: ';'이(가) 'port' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(101,17): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(104,12): error C2065: 'u_long': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(104,12): error C2146: 구문 오류: ';'이(가) 'v4a' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(104,15): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(112,19): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(112,19): warning C4047: '==': 'const sockaddr *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(122,18): error C2037: 'sa_family'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'sockaddr'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(133,10): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(133,41): error C2037: 'si_port'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'gni_sockinet'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(136,22): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(136,22): warning C4047: '==': 'char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(138,38): error C2065: 'NI_NUMERICSERV': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(139,42): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(144,32): error C2065: 'port': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(144,51): error C2065: 'NI_DGRAM': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(144,69): warning C4047: '=': 'servent *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(146,28): error C2037: 's_name'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'servent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(146,34): error C2168: 'strlen': 내장 함수에 대한 실제 매개 변수가 너무 적습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(148,30): error C2037: 's_name'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'servent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(148,36): error C2168: 'strcpy': 내장 함수에 대한 실제 매개 변수가 너무 적습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(153,17): error C2037: 'sa_family'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'sockaddr'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(154,17): error C2065: 'AF_INET': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(155,13): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(155,43): error C2037: 'sin_addr'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'sockaddr_in'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(156,29): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(156,53): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(157,36): error C2065: 'NI_NUMERICHOST': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(158,13): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(158,33): error C2065: 'IN_CLASSA_NSHIFT': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(159,17): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(159,29): error C2065: 'v4a': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(159,46): error C2065: 'IN_LOOPBACKNET': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(160,36): error C2065: 'NI_NUMERICHOST': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(170,22): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(170,22): warning C4047: '==': 'char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(172,38): error C2065: 'NI_NUMERICHOST': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(174,20): error C2065: 'NULL': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(183,68): warning C4047: '=': 'hostent *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(184,26): error C2065: 'h_errno': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(188,34): error C2065: 'NI_NOFQDN': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(189,32): error C2037: 'h_name'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'hostent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(189,44): warning C4047: '=': 'char *'의 간접 참조 수준이 'int'과(와) 다릅니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(192,28): error C2037: 'h_name'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'hostent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(192,34): error C2168: 'strlen': 내장 함수에 대한 실제 매개 변수가 너무 적습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(198,30): error C2037: 'h_name'의 왼쪽은 정의되지 않은 구조체/공용 구조체 'hostent'을(를) 지정합니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(198,36): error C2168: 'strcpy': 내장 함수에 대한 실제 매개 변수가 너무 적습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(203,36): error C2065: 'NI_NAMEREQD': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getnameinfo.c(206,24): error C2065: 'NULL': 선언되지 않은 식별자입니다.
  getpath.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\getpath.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  grpmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\grpmodule.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  hashtable.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\hashtable.c(47,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  itertoolsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\itertoolsmodule.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  main.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\main.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  mathmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\mathmodule.c(55,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  md5module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\md5module.c(19,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  mmapmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\mmapmodule.c(22,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  nismodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\nismodule.c(13,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  ossaudiodev.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\ossaudiodev.c(23,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  overlapped.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\overlapped.c(10,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  parsermodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\parsermodule.c(29,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  posixmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\posixmodule.c(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  pwdmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\pwdmodule.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  pyexpat.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\pyexpat.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  readline.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\readline.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  resource.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\resource.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  rotatingtree.c
  selectmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\selectmodule.c(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  sha1module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\sha1module.c(19,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  sha256module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\sha256module.c(19,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  sha512module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\sha512module.c(19,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  signalmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\signalmodule.c(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  socketmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\socketmodule.c(103,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  spwdmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\spwdmodule.c(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  symtablemodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\symtablemodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  syslogmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\syslogmodule.c(52,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  termios.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\termios.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  timemodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\timemodule.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  tkappinit.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\tkappinit.c(16,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'tcl.h': No such file or directory
  unicodedata.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\unicodedata.c(18,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  xxlimited.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\xxlimited.c(17,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  xxmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\xxmodule.c(17,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  xxsubtype.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\xxsubtype.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  zlibmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\zlibmodule.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _abc.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_abc.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  _asynciomodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_asynciomodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _bisectmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_bisectmodule.c(7,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  blake2b_impl.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_blake2\blake2b_impl.c(16,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  blake2module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_blake2\blake2module.c(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  blake2s_impl.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_blake2\blake2s_impl.c(16,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  blake2-dispatch.c
  blake2b-ref.c
  blake2b-test.c
  blake2b.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_blake2\impl\blake2-config.h(67,1): fatal error C1189: #error:  "This code requires at least SSE2."
  blake2bp-test.c
  blake2bp.c
  blake2s-ref.c
  blake2s-test.c
  blake2s.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_blake2\impl\blake2-config.h(67,1): fatal error C1189: #error:  "This code requires at least SSE2."
  blake2sp-test.c
  blake2sp.c
  _bz2module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_bz2module.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _codecsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_codecsmodule.c(34,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _collectionsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_collectionsmodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _contextvarsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_contextvarsmodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  _cryptmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_cryptmodule.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _csv.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_csv.c(13,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  callbacks.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\callbacks.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  callproc.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\callproc.c(57,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  cfield.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\cfield.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  dlfcn_simple.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\darwin\dlfcn_simple.c(39,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'mach-o/dyld.h': No such file or directory
  ffi.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\libffi_osx\ffi.c(24,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'ffi.h': No such file or directory
  ppc-ffi_darwin.c
  types.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\libffi_osx\types.c(26,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'ffi.h': No such file or directory
  x86-ffi64.c
  x86-ffi_darwin.c
  malloc_closure.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\malloc_closure.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  stgdict.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\stgdict.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _ctypes.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\_ctypes.c(104,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _ctypes_test.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ctypes\_ctypes_test.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _cursesmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_cursesmodule.c(105,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _curses_panel.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_curses_panel.c(13,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _datetimemodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_datetimemodule.c(10,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _dbmmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_dbmmodule.c(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  basearith.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  constants.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  context.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  convolute.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  crt.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  difradix2.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  fnt.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  fourstep.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  io.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  memory.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  mpdecimal.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  numbertheory.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  sixstep.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  transpose.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\libmpdec\mpdecimal.h(227,1): fatal error C1189: #error:  "define CONFIG_64 or CONFIG_32"
  _decimal.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_decimal\_decimal.c(29,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _elementtree.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_elementtree.c(16,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _functoolsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_functoolsmodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _gdbmmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_gdbmmodule.c(7,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _hashopenssl.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_hashopenssl.c(16,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _heapqmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_heapqmodule.c(9,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  bufferedio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\bufferedio.c(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  bytesio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\bytesio.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  fileio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\fileio.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  iobase.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\iobase.c(12,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  stringio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\stringio.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  textio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\textio.c(10,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  winconsoleio.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\winconsoleio.c(10,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _iomodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_io\_iomodule.c(11,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _json.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_json.c(8,1): fatal error C1189: #error:  "Py_BUILD_CORE_BUILTIN or Py_BUILD_CORE_MODULE must be defined"
  _localemodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_localemodule.c(13,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _lsprof.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_lsprof.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _lzmamodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_lzmamodule.c(10,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _math.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_math.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  multiprocessing.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_multiprocessing\multiprocessing.h(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  posixshmem.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_multiprocessing\posixshmem.c(7,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  semaphore.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_multiprocessing\multiprocessing.h(6,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _opcode.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_opcode.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _operator.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_operator.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _pickle.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_pickle.c(8,1): fatal error C1189: #error:  "Py_BUILD_CORE_BUILTIN or Py_BUILD_CORE_MODULE must be defined"
  _posixsubprocess.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_posixsubprocess.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _queuemodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_queuemodule.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  _randommodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_randommodule.c(69,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _scproxy.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_scproxy.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  KeccakHash.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakSponge.h(1,1): warning C4819: 현재 코드 페이지(949)에서 표시할 수 없는 문자가 파일에 들어 있습니다. 데이터가 손실되지 않게 하려면 해당 파일을 유니코드 형식으로 저장하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakSponge.h(149,14): fatal error C1083: 포함 파일을 열 수 없습니다. 'KeccakP-200-SnP.h': No such file or directory
  KeccakP-1600-inplace32BI.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-SnP.h(6,1): fatal error C1189: #error:  "No KeccakOpt"
  KeccakP-1600-opt64.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(52,21): error C2061: 구문 오류: 식별자 'KeccakF1600RoundConstants'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(52,21): error C2059: 구문 오류: ';'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(52,46): error C2059: 구문 오류: '['
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(84,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(84,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(85,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(85,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(86,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(86,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(87,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(87,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(88,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(88,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(89,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(89,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(98,12): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(98,12): error C2146: 구문 오류: ';'이(가) 'lane' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(98,16): error C2065: 'lane': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(102,14): error C2065: 'lane': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(104,14): error C2065: 'lane': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(105,21): error C2065: 'lane': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(107,10): error C2065: 'lane': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(114,13): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(114,14): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(137,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(137,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(138,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(138,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(139,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(139,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(140,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(140,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(141,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(141,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(142,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(142,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(143,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(143,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(144,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(144,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(147,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(147,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(148,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(148,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(149,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(149,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(150,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(150,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(153,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(153,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(154,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(154,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(157,19): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(157,20): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(226,21): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(226,22): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(228,21): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(228,22): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(254,21): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(254,22): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(256,21): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(256,22): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'UINT64': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Aba' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aba': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Abe': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Abi': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Abo': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Abu': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Aga' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aga': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Age': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Agi': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ago': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Agu': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Aka' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aka': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ake': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aki': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ako': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aku': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Ama' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ama': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ame': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ami': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Amo': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Amu': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Asa' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Asa': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Ase': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Asi': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Aso': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Asu': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Bba' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bba': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bbe': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bbi': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bbo': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bbu': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2146: 구문 오류: ';'이(가) 'Bga' 식별자 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): error C2065: 'Bga': 선언되지 않은 식별자입니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakP-1600-opt64.c(276,5): fatal error C1003: 오류 수가 100개를 초과했습니다. 컴파일을 중지합니다.
  KeccakSponge.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakSponge.h(1,1): warning C4819: 현재 코드 페이지(949)에서 표시할 수 없는 문자가 파일에 들어 있습니다. 데이터가 손실되지 않게 하려면 해당 파일을 유니코드 형식으로 저장하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\kcp\KeccakSponge.h(149,14): fatal error C1083: 포함 파일을 열 수 없습니다. 'KeccakP-200-SnP.h': No such file or directory
  sha3module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sha3\sha3module.c(18,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  cache.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\cache.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  connection.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\cache.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  cursor.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\cursor.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  microprotocols.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\microprotocols.c(26,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  module.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\connection.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  prepare_protocol.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\prepare_protocol.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  row.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\row.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  statement.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\statement.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  util.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sqlite\module.h(27,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _sre.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_sre.c(43,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _ssl.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl.c(19,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  debughelpers.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(12,54): error C2143: 구문 오류: ')'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(12,54): error C2081: 'SSL': 정식 매개 변수 목록에 있는 이름이 잘못되었습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(12,54): error C2143: 구문 오류: '{'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(12,65): error C2059: 구문 오류: '형식'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(12,69): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(86,17): error C2143: 구문 오류: '{'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(87,45): error C2143: 구문 오류: ')'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(87,45): error C2143: 구문 오류: '{'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(87,57): error C2059: 구문 오류: '형식'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(87,59): error C2059: 구문 오류: ')'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(97,45): error C2143: 구문 오류: ')'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(97,45): error C2143: 구문 오류: '{'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(97,61): error C2143: 구문 오류: ';'이(가) '*' 앞에 없습니다.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(97,72): error C2059: 구문 오류: '형식'
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_ssl\debughelpers.c(97,74): error C2059: 구문 오류: ')'
  _stat.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_stat.c(15,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  _statisticsmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_statisticsmodule.c(1,1): warning C4819: 현재 코드 페이지(949)에서 표시할 수 없는 문자가 파일에 들어 있습니다. 데이터가 손실되지 않게 하려면 해당 파일을 유니코드 형식으로 저장하십시오.
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_statisticsmodule.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _struct.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_struct.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _testbuffer.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_testbuffer.c(7,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _testcapimodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_testcapimodule.c(15,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _testimportmultiple.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_testimportmultiple.c(6,9): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _testinternalcapi.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_testinternalcapi.c(6,1): fatal error C1189: #error:  "Py_BUILD_CORE_BUILTIN or Py_BUILD_CORE_MODULE must be defined"
  _testmultiphase.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_testmultiphase.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _threadmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_threadmodule.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _tkinter.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_tkinter.c(26,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _tracemalloc.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_tracemalloc.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _uuidmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_uuidmodule.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _weakref.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_weakref.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _winapi.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_winapi.c(37,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _xxsubinterpretersmodule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_xxsubinterpretersmodule.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  fuzzer.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_xxtestfuzz\fuzzer.c(13,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  _xxtestfuzz.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Modules\_xxtestfuzz\_xxtestfuzz.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  abstract.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\abstract.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  accu.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\accu.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  boolobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\boolobject.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  bytearrayobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\bytearrayobject.c(4,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  코드를 생성하고 있습니다...
  컴파일하고 있습니다...
  bytesobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\bytesobject.c(5,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  bytes_methods.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\bytes_methods.c(2,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  call.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\call.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  capsule.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\capsule.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  cellobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\cellobject.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  classobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\classobject.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  codeobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\codeobject.c(3,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
  complexobject.c
C:\Users\ccm13\Desktop\MyProject\Python-3.8.5\Python\Objects\complexobject.c(8,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Python.h': No such file or directory
